---
- name: Configure Router group hosts
  hosts: all
  become: yes
  become_user: root

  environment:
    http_proxy: http://10.0.2.2:3128
    https_proxy: http://10.0.2.2:3128


  tasks:

     - name: port knocking on inetRouter
       template: 
         src: "{{ item.src }}"
         dest: "{{ item.dest }}"
         owner: root
         group: root
         mode: "{{ item.mode }}"
       with_items:
         - { src: "iptables_rules.ipv4", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
         - { src: "iptables_restore", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
       when: (ansible_hostname == "inetRouter")

     - name: rules for inetRouter2
       template: 
         src: "{{ item.src }}"
         dest: "{{ item.dest }}"
         owner: root
         group: root
         mode: "{{ item.mode }}"
       with_items:
         - { src: "iptables_rules.ipv4_inetRouter2", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
         - { src: "iptables_restore", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
       when: inventory_hostname == "inetRouter2"


     - name: set up forward packages across all
       sysctl:
         name: net.ipv4.conf.all.forwarding
         value: '1'
         state: present

     - name: install nginx on centralServer
       apt:
         name: nginx
         state: present
         update_cache: true
       when: (ansible_hostname == "centralServer")

     - name: start nginx
       systemd:
         name: nginx
         state: started
       when: (ansible_hostname == "centralServer")


- name: Configure Router group hosts
  hosts: routers
  become: yes
  become_user: root

  tasks:
    - name: disable default route
      template:
        src: 00-installer-config.yaml
        dest: /etc/netplan/00-installer-config.yaml
        owner: root
        group: root
        mode: 0644

    - name: add default gateway for everyone
      template:
        src: "50-vagrant_{{ansible_hostname}}.yaml"
        dest: /etc/netplan/50-vagrant.yaml
        owner: root
        group: root
        mode: 0644
      when: inventory_hostname != "inetRouter2"

    - name: netplan apply
      command: netplan apply
