name: zabbix_hw
services:


  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    environment:
      - DB_SERVER_HOST=postgres
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Moscow
    ports:
        - 8080:8080
        - 8443:8443
    depends_on: 
        - postgres
        - zabbix-server
#    networks:
#        - main-net


  postgres:
    image: postgres:alpine3.20
    environment:
        - POSTGRES_DB=zabbix
        - POSTGRES_USER=zabbix
        - POSTGRES_PASSWORD=zabbix
#    networks:
#        - main-net


  zabbix-server:
        image: zabbix/zabbix-server-pgsql:trunk-ubuntu
        environment:
                - DB_SERVER_HOST=postgres
                - POSTGRES_DB=zabbix
                - POSTGRES_USER=zabbix
                - POSTGRES_PASSWORD=zabbix
        ports:
                - 10051:10051
  zabbix-agent:
        image: zabbix/zabbix-agent:latest
        environment:
            - ZBX_HOSTNAME=zabbix-agent
            - ZBX_SERVER_HOST=zabbix-server
