MACHINES = {
  :inetRouter => {
    :box_name => "generic/ubuntu2204",
    :vm_name => "inetRouter",
    :net => [
      ["192.168.255.1", 2, "255.255.255.252", "router-net"],
      ["192.168.50.10", 8, "255.255.255.0"],
    ]
  },

  :centralRouter => {
    :box_name => "generic/ubuntu2204",
    :vm_name => "centralRouter",
    :net => [
      ["192.168.255.2", 2, "255.255.255.252", "router-net"],
      ["192.168.0.1", 3, "255.255.255.240", "dir-net"],
      ["192.168.0.33", 4, "255.255.255.240", "hw-net"],
      ["192.168.0.65", 5, "255.255.255.192", "mgt-net"],
      ["192.168.255.9", 6, "255.255.255.252", "office1-central"],
      ["192.168.255.5", 7, "255.255.255.252", "office2-central"],
      ["192.168.50.11", 8, "255.255.255.0"],
    ]
  },

  :centralServer => {
    :box_name => "generic/ubuntu2204",
    :vm_name => "centralServer",
    :net => [
      ["192.168.0.2", 2, "255.255.255.240", "dir-net"],
      ["192.168.50.12", 8, "255.255.255.0"],
    ]
  }
}

Vagrant.configure("2") do |config|

  config.vm.define "inetRouter2" do |inetRouter2|
    inetRouter2.vm.network "private_network", ip: "192.168.50.1", netmask: "255.255.255.0"
    inetRouter2.vm.network "private_network", ip: "192.168.60.10", netmask: "255.255.255.0"
    inetRouter2.vm.network "forwarded_port", guest: 8080, host: 8080
    inetRouter2.vm.box = "generic/ubuntu2204"
  end

  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]

      box.vm.provider "virtualbox" do |v|
        v.memory = 768
        v.cpus = 1
      end

      boxconfig[:net].each do |ipconf|
        box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
      end

      if boxconfig.key?(:public)
        box.vm.network "public_network", boxconfig[:public]
      end

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL
    end
  end

  # Ansible provision будет выполнен в конце
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yaml"
    ansible.inventory_path = "ansible/inventory"
    ansible.host_key_checking = "false"
    ansible.limit = "all"
  end
end

