#Запуск ролей install_postgres и postgres_replication на хостах node1 и node2
- name: install postgres 14 and set up replication
  hosts: node1,node2
  become: yes
  environment:                        
    http_proxy: http://10.0.2.2:3128  
    https_proxy: http://10.0.2.2:3128 
  roles:
   - install_postgres
   - postgres_replication

#Запуск роли install_barman на всех хостах
- name: set up backup
  hosts: all
  environment:                        
   http_proxy: http://10.0.2.2:3128  
   https_proxy: http://10.0.2.2:3128 
  become: yes
  roles:
   - install_barman

